theme: jekyll-theme-chirpy

lang: ko-KR
timezone: Asia/Seoul

title: "산의 개발·보안 블로그"
tagline: "개발과 보안을 공부하는 기록"
description: >-
  개발, 보안 공부, CTF 풀이와 연구 활동을 기록하는 개인 블로그입니다.

url: "https://leesan0919.github.io"
baseurl: ""

github:
  username: LeeSan0919

twitter:
  username:

social:
  name: 이산
  email:
  fediverse_handle:
  links:
    - https://github.com/LeeSan0919

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

pageviews:
  provider:

theme_mode:
cdn:
avatar:
social_preview_image:

toc: true

actions:
  edit_post:
    enabled: false
    url: ""
    static_url: false

comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

assets:
  self_host:
    enabled: false
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: []

paginate: 10

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/

  - scope:
      path: _drafts
    values:
      comments: false

  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
